-- SQLite

CREATE TABLE msgs (
	id INTEGER PRIMARY KEY,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	sender TEXT NOT NULL,
	message TEXT NOT NULL
);

CREATE TABLE users (
	id INTEGER PRIMARY KEY,
	registered DATETIME DEFAULT CURRENT_TIMESTAMP,
	username TEXT NOT NULL,
	hash TEXT NOT NULL,
	avatar INT DEFAULT 0
);

